# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1dcd25e50470d56b0a99b372567e15d6fb68db959c3786ac89068ea9ed3a073742751a4c005f1a564419a52e7fae331fbc61c3107f379939d1bf3895a358355d

test:
  secret_key_base: 7c3b76a672a9e13b9c20d938bb5db77eea32266876f23c1d42cc7828eb04665beff3bcbd7e10b27144a39f8c59881a1cfea3c7ec97cabff08b9e9dbdee67f57b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
